config/routes.rb
Rails.application.routes.draw do
 # URL /customers/sign_in ...
 devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

 # ゲストログイン用
 devise_scope :end_user do
  post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
 end



 # 管理者用
 # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: 'public/homes#top'
  get 'homes/about' => "public/homes#about", as: :about
  get "search" => "searches#search"
 

  namespace :admin do
    get 'homes/top' => 'homes#top'


    resources :end_users, only: [:index, :show, :edit, :update]
    resources :ingredients
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :recipes, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]

  end


  scope module: :public do
    # 顧客用
    get 'end_users/:id/reregistration', to: 'end_users#reregistration', as: 'reregistration'
     # 退会確認画面
    get  '/end_users/:id/check' => 'end_users#check', as: 'check'
     # 論理削除用のルーティング
    patch '/end_users/:id/withdraw' => 'end_users#withdraw', as: 'withdraw'

    # devise_scope :user do
      # post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # end
    get 'recipes/tag/:name', to: "recipes#tag_search"
    get 'recipes/search', to: 'recipes#search'

    # resources :end_users, params: :account do
    resources :end_users do
     member do
      # いいねした一覧
      get :liked_recipes
     end
    end
    
    resources :ingredients, only: [:index, :show]
    resources :recipes do
     resource :favorite, only: [:create, :destroy]
     resources :post_comments, only: [:create, :destroy, :index]
    end

    resources :categories, only: [:index] do
     resources :ingrdients, only: :index, module: :categories
    end
    
    resources :notifications, only: [:index, :destroy]

  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :end_user
  belongs_to :recipe
  #コメント返信機能のため下記2行追加
  belongs_to :parent, class_name: "PostComment", optional: true
  has_many :replies, class_name: "PostComment", foreign_key: :parent_id, dependent: :destroy
  
  validates :comment, presence: true
  
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController

  def index
    @post_comments = PostComment.order(created_at: :desc).page(params[:page]).per(10)
    @end_users = EndUser.all
  end

  def destroy
    @post_comment = PostComment.find(params[:id])
    @post_comment.destroy
    redirect_back(fallback_location: admin_post_comments_path)
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/_index.html.erb
<h4 class="heading-title">
  <%= "#{@end_user.family_name} #{@end_user.first_name}(#{@end_user.nickname})" %>さんの投稿コメント一覧
  (<%= @end_user.post_comments.count %>件)
</h4>
<table class="table mt-3">
  <tr>
    <th class="col-2">作成日</th>
    <th class="col-9">コメント</th>
    <th class="col-1"></th>
  </tr>
<% @end_user.post_comments.order(created_at: :desc).each do |post_comment| %>
  <tr>
    <td class="col-2"><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
    <td class="col-9"><%= post_comment.comment %></td>
    <td class="col-1">
      <%= link_to '削除', admin_post_comment_path(post_comment), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-sm btn-danger" %>
    </td>
  </tr>
<% end %>
</table>

app/views/admin/post_comments/index.html.erb
<div class="container mt-5">
  <div class="row" style="margin-bottom: 20px;">
    <h3>投稿コメント一覧</h3>
<table class="table mt-3">
  <tr>
    <th class="col-2">名前</th>
    <th class="col-8">コメント</th>
    <th class="col-1">作成日</th>
    <th class="col-1"></th>
  </tr>
<% @post_comments.each do |post_comment| %>
  <tr>
    <td class="col-2">
      <%= link_to admin_end_user_path(post_comment.end_user_id) do %>
        <%= @end_users.find(post_comment.end_user_id).nickname %>
      <% end %>
    </td>
    <td class="col-8">
      <%= link_to admin_recipe_path(post_comment.recipe_id) do %>
        <%= post_comment.comment %>
      <% end %>
    </td>
    <td class="col-1"><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
    <td class="col-1">
    <%= link_to '削除', admin_post_comment_path(post_comment), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-sm btn-danger" %>
    </td>
  </tr>
<% end %>
</table>
</div>

<div class="row justify-content-center" style="margin-bottom: 20px;">
  <%= paginate @post_comments %>
</div>
</div>