config/routes.rb
Rails.application.routes.draw do
 # URL /customers/sign_in ...
 devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

 # ゲストログイン用
 devise_scope :end_user do
  post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
 end



 # 管理者用
 # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: 'public/homes#top'
  get 'homes/about' => "public/homes#about", as: :about
  get "search" => "searches#search"
 

  namespace :admin do
    get 'homes/top' => 'homes#top'


    resources :end_users, only: [:index, :show, :edit, :update]
    resources :ingredients
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :recipes, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]

  end


  scope module: :public do
    # 顧客用
    get 'end_users/:id/reregistration', to: 'end_users#reregistration', as: 'reregistration'
     # 退会確認画面
    get  '/end_users/:id/check' => 'end_users#check', as: 'check'
     # 論理削除用のルーティング
    patch '/end_users/:id/withdraw' => 'end_users#withdraw', as: 'withdraw'

    # devise_scope :user do
      # post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # end
    get 'recipes/tag/:name', to: "recipes#tag_search"
    get 'recipes/search', to: 'recipes#search'

    # resources :end_users, params: :account do
    resources :end_users do
     member do
      # いいねした一覧
      get :liked_recipes
     end
    end
    
    resources :ingredients, only: [:index, :show]
    resources :recipes do
     resource :favorite, only: [:create, :destroy]
     resources :post_comments, only: [:create, :destroy, :index]
    end

    resources :categories, only: [:index] do
     resources :ingrdients, only: :index, module: :categories
    end
    
    resources :notifications, only: [:index, :destroy]

  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "カテゴリーを新規作成しました"
    else
      render :index
    end  
  end

  def index
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    if category.update(category_params)
      redirect_to admin_categories_path, notice: "カテゴリー情報を更新しました"
    else
      render :index
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to request.referer, notice: "カテゴリー情報を削除しました"
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class= 'container mt-5'>
  <div class="col-md-10 mx-auto mt-5">
    <h4>編集</h4>
      <%= form_with model: @category, url: admin_category_path(@category), method: :patch do |f| %>
    <h4>カテゴリー名</h4>
      <%= f.text_field :name %>
      <%= f.submit '編集を保存' %>
      <% end %>
  </div>
</div>  

app/views/admin/categories/index.html.erb
<div class= 'container-fluid'>


    <div class="row">
      <div class="col-4">
        <div class="row">
      <div class="col headline">
        <h4>＜カテゴリー一覧・新規追加＞</h4>
      </div>
    </div>

    <div class="row">
      <div class="col headline">
        <%= form_with model: Category.new, url:admin_categories_path, method: :post do |f| %>
          <h5><strong>カテゴリー名新規作成</strong></h5>
          <%= f.text_field :name %>
          <%= f.submit 'カテゴリーを増やす' %>
        <% end %>
      </div>
    </div>

  　<table class ="table table-bordered border-dark table-hover align-middle custom-table">
      <thead class ="table-head" style="background-color:#6ea7a1;">
        <tr align="center">
         <th scope="col" style="width: 50%">カテゴリー名</th>
         <th scope="col" style="width: 25%"></th>
         <th scope="col" style="width: 25%"></th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category|%>
        <tr align="center">
          <td>
            <%= category.name %>
          </td>
          <td>
            <%= link_to "編集", edit_admin_category_path(category.id) %>
          </td>
          <td>
            <%= link_to "削除", admin_category_path(category.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
      </div>
      <div class="col-8">
        <%= render 'public/categories/index', categories: @categories, admin: true %>
      </div>
    </div>



</div>