config/routes.rb
Rails.application.routes.draw do
 # URL /customers/sign_in ...
 devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

 # ゲストログイン用
 devise_scope :end_user do
  post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
 end



 # 管理者用
 # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: 'public/homes#top'
  get 'homes/about' => "public/homes#about", as: :about
  get "search" => "searches#search"
 

  namespace :admin do
    get 'homes/top' => 'homes#top'


    resources :end_users, only: [:index, :show, :edit, :update]
    resources :ingredients
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :recipes, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]

  end


  scope module: :public do
    # 顧客用
    get 'end_users/:id/reregistration', to: 'end_users#reregistration', as: 'reregistration'
     # 退会確認画面
    get  '/end_users/:id/check' => 'end_users#check', as: 'check'
     # 論理削除用のルーティング
    patch '/end_users/:id/withdraw' => 'end_users#withdraw', as: 'withdraw'

    # devise_scope :user do
      # post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    # end
    get 'recipes/tag/:name', to: "recipes#tag_search"
    get 'recipes/search', to: 'recipes#search'

    # resources :end_users, params: :account do
    resources :end_users do
     member do
      # いいねした一覧
      get :liked_recipes
     end
    end
    
    resources :ingredients, only: [:index, :show]
    resources :recipes do
     resource :favorite, only: [:create, :destroy]
     resources :post_comments, only: [:create, :destroy, :index]
    end

    resources :categories, only: [:index] do
     resources :ingrdients, only: :index, module: :categories
    end
    
    resources :notifications, only: [:index, :destroy]

  end

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> obj from being saved:prohibited this </h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-auto py-3">
      <div class="container-fluid">
        <div class="row justify-content-center">
          <i class="fa-regular fa-copyright">Chef's Table</i>
        </div>
      </div>
        
</footer>

app/views/layouts/_header.html.erb
      <header class="sticky-top" style="background-color: #9ba5a0; color: #eaedf7;">

          <div class = "container-fluid ">
              <div class="row mx-auto">
                    <div class="col-2 my-4">
                      <%= link_to root_path do %>
                        <h1 class="logo-img"></h1>
                      <% end %>
                      <%= link_to root_path, style: "color: white;" do %>
                        <h6 class="logo-text">Chef's Table</h6>
                      <% end %>
                    </div>


                    <div class="col-3 my-4">
                      <% if end_user_signed_in?%>
                        <p><%= "ようこそ！#{current_end_user.nickname} さん" %></p>
                      <% end %>
                    </div>

                    <!--admin login時header-->
                    <div class="col-7">
                      <ul class="row justify-content-end my-2 list-unstyled">
                        <% if admin_signed_in? %>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to admin_end_users_path, style: "color: white;" do %>
                              <i class="fa-solid fa-users"></i>会員一覧
                            <% end %>
                          </li>

                          <li class="nav-item mx-2 my-4">
                            <%= link_to admin_recipes_path, style: "color: white;" do %>
                              <i class="fa-solid fa-bowl-food"></i>レシピ一覧
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to admin_post_comments_path, style: "color: white;" do %>
                              <i class="fa-solid fa-bowl-food"></i>コメント一覧
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to  admin_categories_path, style: "color: white;" do %>
                              <i class="fa-regular fa-clipboard"></i>食材カテゴリー一覧
                            <% end %>
                          </li>
                           <li class="nav-item mx-2 my-4">
                            <%= link_to  new_admin_ingredient_path, style: "color: white;" do %>
                              <i class="fa-solid fa-folder-open"></i>食材図鑑追加フォーム
                            <% end %>
                         </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to  destroy_admin_session_path, style: "color: white;", method: :delete do %>
                              <i class="fa-solid fa-arrow-right-from-bracket"></i>ログアウト
                            <% end %>
                          </li>

                          <!--end_userlogin時header-->
                         <% elsif end_user_signed_in? %>
                          <li class="nav-item mx-2 my-4">
                            <% if unchecked_notifications.any? %>
                              <div class="notice_box">
                                <%= link_to notifications_path, style: "color: white" do %>
                                  <i class="fa-solid fa-bell"></i>Notice
                                <% end %>
                              </div>
                            <% else %>
                              <%= link_to notifications_path, style: "color: white" do %>
                                <i class="fa-solid fa-check"></i>Notice
                              <% end %>
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to end_user_path(current_end_user), style: "color: white;" do %>
                              <i class="fa-solid fa-mug-hot"></i>マイページ
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to liked_recipes_end_user_path(current_end_user), data: {"turbolinks" => false}, style: "color: white;" do %>
                              <i class="fa-solid fa-mug-hot"></i>いいねした投稿
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to recipes_path, style: "color: white;" do %>
                              <i class="fa-solid fa-bowl-food"></i>レシピ一覧
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to new_recipe_path, data: {"turbolinks" => false}, style: "color: white;" do %>
                              <i class="fa-solid fa-clipboard"></i>新規投稿ページ
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to end_users_path, style: "color: white;" do %>
                              <i class="fa-solid fa-address-book"></i>会員一覧
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to categories_path, style: "color: white;" do %>
                              <i class="fa-solid fa-book-open"></i>食材図鑑
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to destroy_end_user_session_path, style: "color: white;", method: :delete do %>
                              <i class="fa-solid fa-arrow-right-from-bracket"></i>ログアウト
                            <% end %>
                          </li>

                        <% else %>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to about_path, style: "color: white;" do %>
                              <i class="fa-solid fa-carrot"></i>アバウト
                            <% end %>
                          </li>
                         <li class="nav-item mx-2 my-4">
                            <%= link_to recipes_path, style: "color: white;" do %>
                              <i class="fa-solid fa-burger"></i>レシピ一覧
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to new_end_user_registration_path, style: "color: white;" do %>
                              <i class="fa-solid fa-user-plus"></i>新規登録
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to new_end_user_session_path, style: "color: white;" do %>
                              <i class="fa-solid fa-arrow-right-to-bracket"></i>ログイン
                            <% end %>
                          </li>
                          <li class="nav-item mx-2 my-4">
                            <%= link_to end_users_guest_sign_in_path, method: :post, style: "color: white;" do %>
                              <i class="fa-solid fa-arrow-right-to-bracket"></i>ゲストログイン
                            <% end %>
                          </li>
                        <% end %>
                      </ul>

                      <div class="row justify-content-end my-2 list-unstyled">

                        <div style="margin-right: 30px; margin-bottom: 15px;">
                          <%= render 'searches/form' %>
                        </div>

                      </div>


              </div>
          </div>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chef's Table</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/1ccc9ca859.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="<%= controller_name == 'homes' && action_name == 'top' ? 'top-page' : '' %>">
    <%= render 'layouts/header' %>
    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>